version: '3'

services:
  spark-master:
    container_name: spark-master
    hostname: spark-master
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./config:/opt/bitnami/spark/config
      - ./jobs:/opt/bitnami/spark/jobs
      - ./datasets:/opt/bitnami/spark/datasets
      - ./utils:/opt/bitnami/spark/utils
      - ./requirements.txt:/requirements.txt
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - tanmay-network

  spark-worker:
    &worker
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./config:/opt/bitnami/spark/config
      - ./jobs:/opt/bitnami/spark/jobs
      - ./datasets:/opt/bitnami/spark/datasets
      - ./utils:/opt/bitnami/spark/utils
      - ./requirements.txt:/requirements.txt
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - tanmay-network

  spark-worker-2:
    <<: *worker
    container_name: spark-worker-2
    hostname: spark-worker-2

  spark-worker-3:
    <<: *worker
    container_name: spark-worker-3
    hostname: spark-worker-3

  spark-worker-4:
    <<: *worker
    container_name: spark-worker-4
    hostname: spark-worker-4

#  spark-worker-5:
#    <<: *worker
#    container_name: spark-worker-5
#    hostname: spark-worker-5

networks:
  tanmay-network: